# Generated by Django 4.2.23 on 2025-08-29 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('MANZANO', 'Manzano'), ('CEREZO', 'Cerezo')], default='MANZANO', max_length=20)),
                ('region', models.CharField(max_length=60)),
                ('comuna', models.CharField(max_length=80)),
                ('superficie_ha', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad_arbol_anios', models.PositiveIntegerField()),
                ('densidad_arboles_ha', models.PositiveIntegerField()),
                ('sistema_riego', models.CharField(choices=[('GOTEO', 'Goteo'), ('ASPERSION', 'Aspersión'), ('SURCO', 'Surco')], default='SURCO', max_length=20)),
                ('produccion_esperada_t', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('proyeccion_json', models.TextField(blank=True, default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
