<<<<<<< HEAD
# Generated by Django 4.2.23 on 2025-08-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


=======
# Generated for AgroPredict Styled MVP
from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion

>>>>>>> 1929edb89119ee1b7292b948c6f40e50284b9889
class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('especie', models.CharField(choices=[('MANZANO', 'Manzano'), ('CEREZO', 'Cerezo')], default='MANZANO', max_length=16)),
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana', 'Metropolitana'), ('O’Higgins', 'O’Higgins'), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], max_length=32)),
                ('comuna', models.CharField(max_length=64)),
                ('superficie_ha', models.FloatField()),
                ('edad_arbol_anios', models.PositiveIntegerField()),
                ('densidad_arboles_ha', models.PositiveIntegerField()),
                ('sistema_riego', models.CharField(choices=[('GOTEO', 'Goteo'), ('ASPERSION', 'Aspersión'), ('SURCO', 'Surco')], default='GOTEO', max_length=12)),
                ('temp_prom_anual_c', models.FloatField(blank=True, null=True)),
                ('precip_anual_mm', models.FloatField(blank=True, null=True)),
                ('radiacion_anual_wm2', models.FloatField(blank=True, null=True)),
                ('produccion_esperada_t', models.FloatField()),
                ('proyeccion_json', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
=======
                ('region', models.CharField(choices=[('Arica y Parinacota', 'Arica y Parinacota'), ('Tarapacá', 'Tarapacá'), ('Antofagasta', 'Antofagasta'), ('Atacama', 'Atacama'), ('Coquimbo', 'Coquimbo'), ('Valparaíso', 'Valparaíso'), ('Metropolitana', 'Metropolitana'), ('O’Higgins', 'O’Higgins'), ('Maule', 'Maule'), ('Ñuble', 'Ñuble'), ('Biobío', 'Biobío'), ('La Araucanía', 'La Araucanía'), ('Los Ríos', 'Los Ríos'), ('Los Lagos', 'Los Lagos'), ('Aysén', 'Aysén'), ('Magallanes', 'Magallanes')], max_length=40)),
                ('arbol_frutal', models.CharField(choices=[('manzana', 'Manzana'), ('cereza', 'Cereza')], default='manzana', max_length=16)),
                ('superficie_ha', models.FloatField()),
                ('temp_prom_anual_c', models.FloatField()),
                ('precip_anual_mm', models.FloatField()),
                ('radiacion_anual_wm2', models.FloatField()),
                ('produccion_esperada_t', models.FloatField()),
                ('proyeccion_json', models.TextField(help_text='JSON de 5 periodos')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-creado']},
>>>>>>> 1929edb89119ee1b7292b948c6f40e50284b9889
        ),
    ]
